version: "3"
services:
  nakama:
    image: docker.io/rishiratanmishra1/nakama-tictactoe:latest
    restart: always
    environment:
      # Use the new Managed Azure PostgreSQL connection string
      NAKAMA_DATABASE_ADDRESS: "dbadmin:Nakama_Db_2026!@nakama-db-tictactoe.postgres.database.azure.com:5432/nakama?sslmode=require"
      NAKAMA_NETWORK_ALLOWED_ORIGINS: "*"
    # Single-line startup: Migrate once, then start server
    command: >
      sh -c "/nakama/nakama migrate up --database.address dbadmin:Nakama_Db_2026!@nakama-db-tictactoe.postgres.database.azure.com:5432/nakama?sslmode=require && 
             /nakama/nakama --database.address dbadmin:Nakama_Db_2026!@nakama-db-tictactoe.postgres.database.azure.com:5432/nakama?sslmode=require --network.allowed_origins '*'"
