services:
  postgres:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_PASSWORD=localdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nakama:
    image: heroiclabs/nakama:3.25.0
    entrypoint:
      - /bin/sh
      - -ecx
      - >
        /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama &&
        /nakama/nakama --config /nakama/data/local.yml --database.address postgres:localdb@postgres:5432/nakama
    restart: always
    links:
      - "postgres:db"
    depends_on:
      - postgres
    volumes:
      - ./backend/data:/nakama/data
      - ./backend/build:/nakama/data/modules
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
